[pytest]
testpaths = devutils
python_files = test_*.py
addopts = -p no:cacheprovider --basetemp=build/pytest-suite
norecursedirs = build chromium_src ungoogled-chromium .git .pytest_cache .ruff_cache
